[package]
name = "zencrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.10"
rpassword = "7"
ring = "0.16"
dialoguer = "0.10"
sha2 = "0.10"
hex = "0.4"
anyhow = "1"
